Repository GSM-MSG/GUI-BackEnd, pull requests merged in 2023-01, with the labels that each got.

#1 🔀 기본세팅
  .gitignore
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
  src/main/kotlin/com/gui/backend/BackendApplication.kt
  src/test/kotlin/com/gui/backend/BackendApplicationTests.kt
Labels: ⚙ Setting

#3 [ADD] RedisConfig
  .gitignore
  src/main/kotlin/com/gui/backend/global/redis/RedisConfig.kt
  src/main/kotlin/com/gui/backend/global/redis/properties/RedisProperties.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#5 BaseEntity 추가
  src/main/kotlin/com/gui/backend/BackendApplication.kt
  src/main/kotlin/com/gui/backend/global/base/entity/BaseIdEntity.kt
  src/main/kotlin/com/gui/backend/global/base/entity/BaseTimeEntity.kt
  src/main/resources/application.yml
Labels: 3️⃣ Priority: Low, ✨ Feature

#9 🚀 :: cloudType에 배포환경 구축
  .gitignore
  src/main/resources/application.yml
Labels: 1️⃣ Priority: High, 🌏 Deploy
